### PR TITLE
Preparing gsops 2.0 early access release

### PR DESCRIPTION
**Pull request by rubendhz**
- After having identified some issues after the latest shader changes, this PR is to temporarily revert some of those for "GSOPs 2.0 Early Access" until they are properly debugged in an upcoming version.

- This PR also removes the 20.0 version of the plugin as this is no longer provided by default.

- Minor updates to example hip file

- Improved logger logic to be less spammy, (which was specially bad when blasting SH attributes on time dependent geometries)

- Added reference to GSOPs 2.0 on README.

- Bumped version to 1.3.0

### CODE REVIEW

**Comment by david-rhodes** [comment]
The logs are spammy when doing anything related to the timeline. I get this when changing the current frame in https://github.com/david-rhodes/GSOPs/blob/develop/hip/basic_usage.hipnc.
image

Can you think of a simple fix? Maybe a button the gsplat source which prints info? Or a "do only once" callback setup?

**Comment by david-rhodes** [comment]
Other than the spam, everything looks good and works as expected. 
Validated while doing this: https://github.com/david-rhodes/GSOPs_Renderer/pull/5.

**Comment by david-rhodes** [comment]
Oh, 20.5 .dll can be found here: https://trello.com/c/x5N8aLJp/7-gsops-20-early-access-checklist

**Comment by rubendhz** [comment]
> The logs are spammy when doing anything related to the timeline. I get this when changing the current frame in https://github.com/david-rhodes/GSOPs/blob/develop/hip/basic_usage.hipnc. image
> 
> Can you think of a simple fix? Maybe a button the gsplat source which prints info? Or a "do only once" callback setup?

Simple fix is I switch to the logger’s “log only once” mode, although, it’d mean it doesn’t log the warning ever again whether different frame or different geometry which can be misleading.

The issue with the button is the same as with “render modes” or “debug attributes “ I need to find a proper way to set those globally for the renderer.

Soooo…. Proper solution is a global toggle I think (I don’t know how to do that at the moment). Temporary “solution” is to switch the logger to “Log only once” and include a “this message is logged only once” bit to prevent being misleading 

wdyt?

**Comment by david-rhodes** [comment]
Well, I do like the aspect that if you pass in different geo, it will give you updated information, especially if there is an error or warning. 

I know that with Python you can have callbacks like `on input changed`. Could we somehow leverage this? Maybe the HDK has a similar hook? 

Otherwise, could we leverage an env variable? I can easily set those up in the package, if you can read them in your plug-in.

**Comment by rubendhz** [comment]
> Well, I do like the aspect that if you pass in different geo, it will give you updated information, especially if there is an error or warning.
> 
> I know that with Python you can have callbacks like `on input changed`. Could we somehow leverage this? Maybe the HDK has a similar hook?
> 
> Otherwise, could we leverage an env variable? I can easily set those up in the package, if you can read them in your plug-in.

the thing with onInputChanged is that it only fires when rewiring, if I remember correctly. As in, you could be changing the geometry upstream with a wrangle or whatever, and there's no event being fired. 

I am gonna try to come up with something that is as self-contained as possible. will report back asap.

**Comment by rubendhz** [comment]
> > Well, I do like the aspect that if you pass in different geo, it will give you updated information, especially if there is an error or warning.
> > I know that with Python you can have callbacks like `on input changed`. Could we somehow leverage this? Maybe the HDK has a similar hook?
> > Otherwise, could we leverage an env variable? I can easily set those up in the package, if you can read them in your plug-in.
> 
> the thing with onInputChanged is that it only fires when rewiring, if I remember correctly. As in, you could be changing the geometry upstream with a wrangle or whatever, and there's no event being fired.
> 
> I am gonna try to come up with something that is as self-contained as possible. will report back asap.

@david-rhodes, Branch is ready for you to give it another go on Windows. Fingers crossed everything working as expected. please let me know (and send me the compiled binary if it's all good)

**Comment by david-rhodes** [comment]
LGTM! 

Windows binary updated here: https://trello.com/c/x5N8aLJp/7-gsops-20-early-access-checklist

**Review by david-rhodes — APPROVED** [review]
Let's go!!! :)

**Pull request merged**
